name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: GSS_Willie_Test
          cx_tenant: galaxysoftware
          base_uri: https://sng.ast.checkmarx.net
          branch: github-action-demo
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --report-format pdf --output-name GSS_Report --output-path .
      
      - name: Upload Checkmarx Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gss-TMD-report
          path: GSS_Report.pdf
